### ISSUE TITLE
Eliminate render-blocking CSS - Issue

### ISSUE THREAD

**Issue by chinmayrajyaguru** [kasparsd/minit#111]
I have just installed on my WordPress website. [Google Page Insights](https://developers.google.com/speed/pagespeed/insights) show error:

> Eliminate render-blocking CSS in above-the-fold content
> `https://example.com/wp-content/uploads/minit/c1c86a2fa4414bc20627f3db92ceee96.css`

This plugin is handling JS files very well but issues with the only CSS combined file - not defer / async.

Kindly resolve this.
Thank you!

**Comment by kasparsd** [comment]
Thanks for reporting the issue @chinmayrajyaguru!

The CSS `<link />` doesn't support `async` and `defer`. The suggested solution is to use JS to add the `link` element, however that is not a good default.

Finally, it is my personal opinion that CSS should be blocking as long as it's a single file because of flash of unstyled content (FOUC) and JS needing to know the actual position of elements on the page.

**Comment by chinmayrajyaguru** [comment]
Thank you for your instant support.

I'm interested to know **how can I use JS to add the `link` element** while using `#Minit`?

It would be great if you will explain it with an example, @kasparsd sir...

Thank you!
